class BitSet:
    def __init__(self, size: int) -> None:
        ...

    def __getitem__(self, index: int) -> bool:
        ...

    def __setitem__(self, index: int, value: bool) -> None:
        ...

    def __contains__(self, index: int) -> bool:
        ...

    def __len__(self) -> int:
        ...

    def __repr__(self) -> str:
        ...

    def elements(self) -> frozenset[int]:
        ...

    @property
    def _blocks(self) -> tuple[int, ...]:
        ...
